export { default as Auth } from './Auth'
export { default as CreateWorkout } from './CreateWorkout'
export { default as Favorites } from './Favorites'
export { default as InstEditProfile } from './InstEditProfile'
export { default as InstMain } from './InstMain'
export { default as InstStatistic } from './InstStatistic'
export { default as Main } from './Main'
export { default as Profile } from './Profile'
export { default as ProfileEdit } from './ProfileEdit'
export { default as Registration } from './Registration'
export { default as Workouts } from './Workouts'
export { default as Register} from './Auth/Register'
export { default as ResetPassword } from './Auth/ResetPassword'
export { default as CodeScreen} from './CodeInput'
export { default as InstWorkouts} from './CreateWorkout/Workouts'
export { default as Withdraw} from './Edit/Withdraw'
export { default as Photo } from './Edit/Photo'
export { default as Invertory} from './Edit/Invertory'
export { default as Skills } from './Edit/Skills'
export { default as Support} from './Edit/Support'
export {default as Address} from './CreateWorkout/Address'
export {default as Date} from './CreateWorkout/Date'
export {default as HistoryWorkout} from './CreateWorkout/HistoryWorkout'
export {default as OpenWorkout} from './CreateWorkout/OpenWorkout'
export {default as Time} from './CreateWorkout/Time'
export {default as Week} from './CreateWorkout/Week'
export { default as Reviews } from './Reviews'
export { default as UserRegistration} from './UserRegistration'
export { default as FirstBalans } from './Auth/FirstBalans'
export { default as ReplyReviews} from './ReplyReviews'
export { default as FAQ} from './Edit/faq'
export { default as UserCard} from './User/UserCard'
export { default as UserFaq} from './User/UserFaq'
export {default as RequestWorkout} from './RequestWorkout'